language: ruby
rvm:
  - 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: PSRCpCrW8KNEGq3Ec+trzHL53FGhPwpeSmalZjIh8LceoBpfVxmCZE8r2PwmodImdo9lTbYrNxNkXwQvXsCQZbi2aH9fbBWvUgFMvPE6sCIwA77a+BiSyyqS1ztMovRbPB+9hcd/tAlSXgw1Tz/zlXWhknLCW9FhGuBQG96ie2a9etyaTV/RESuUQEsIgY92taSAcnufstKMM5wrrLwcAcAcd3sscO09660RAS8fD923sRhgiNnRlyMuJ8E5Ig2T4X/nNGISpHOwUd0yqyU2z8Zo93NmCqfa9tK5xu9kRSTdsqwJ5uL/SX4z2sRPRFoctemPuYM6hJQm5scwh6yw6wFkWvYSG1QhaEr67Euc/z0nM4O7uiex3zulSxJ/NwOxy0Z9AJPGH2t2V/lbwy0dStK6FogrwEPbl8EuvXvCnc3vES0QsDPgI6ZSUbDHrHR42X875JC8UPgWmO97nca4keERVDSkUVy+dzey0gR7msELMCx9duC9rvJlkzj+gkJ+1Uhh9LAn64zwvnVtGE/nkJg7oEgJHDdiOm+PXL6CmGS0H56x0UcDqLA1Oqw9fbBoC80XuPyHHPWJ/Qn0fBZeK4LufJCJ10lAYLTHJawykYr98p2dIgvXeQqz1L4ViYVEJYpDf9i75OZtUI3X2HIINA9nNEW1CCIHrWLaue4uhPk=
